import { FAQ, Service, Page, Section, SiteSettings } from './types';

export const defaultServices: Omit<Service, 'id' | 'created_at' | 'updated_at'>[] = [
  {
    slug: 'custom-app-development',
    icon: 'Smartphone',
    title_en: 'Custom App Development',
    title_fr: 'Développement d\'Applications Personnalisées',
    title_ar: 'تطوير تطبيقات مخصصة',
    title_de: 'Individuelle App-Entwicklung',
    description_en: 'From MVPs to full platforms, we design and build mobile and web apps tailored to your business and your users.',
    description_fr: 'Des MVP aux plateformes complètes, nous concevons et construisons des applications mobiles et web adaptées à votre entreprise et à vos utilisateurs.',
    description_ar: 'من المنتجات الأولية إلى المنصات الكاملة، نصمم ونبني تطبيقات الجوال والويب المصممة خصيصًا لعملك ومستخدميك.',
    description_de: 'Von MVPs bis zu vollständigen Plattformen entwerfen und entwickeln wir mobile und Web-Apps, die auf Ihr Unternehmen und Ihre Nutzer zugeschnitten sind.',
    features_en: ['MVP Development', 'Full Platform Solutions', 'Mobile Apps', 'Web Applications'],
    features_fr: ['Développement MVP', 'Solutions de Plateformes Complètes', 'Applications Mobiles', 'Applications Web'],
    features_ar: ['تطوير المنتج الأولي', 'حلول المنصات الكاملة', 'تطبيقات الجوال', 'تطبيقات الويب'],
    features_de: ['MVP-Entwicklung', 'Vollständige Plattformlösungen', 'Mobile Apps', 'Webanwendungen'],
    price_range_dzd: '500,000 - 2,000,000 DZD',
    price_range_eur: '2,500 - 10,000 €',
    price_range_usd: '$2,500 - $10,000',
    is_featured: true,
    display_order: 1,
  },
  {
    slug: 'websites',
    icon: 'Globe',
    title_en: 'Websites that convert',
    title_fr: 'Sites web qui convertissent',
    title_ar: 'مواقع ويب تحقق النتائج',
    title_de: 'Websites, die konvertieren',
    description_en: 'Modern, fast, and responsive websites that make you look professional and turn visitors into clients.',
    description_fr: 'Des sites web modernes, rapides et réactifs qui vous donnent un air professionnel et transforment les visiteurs en clients.',
    description_ar: 'مواقع ويب حديثة وسريعة ومتجاوبة تجعلك تبدو محترفًا وتحول الزوار إلى عملاء.',
    description_de: 'Moderne, schnelle und responsive Websites, die Sie professionell aussehen lassen und Besucher in Kunden verwandeln.',
    features_en: ['Modern Design', 'Fast Loading', 'Responsive', 'Professional Look'],
    features_fr: ['Design Moderne', 'Chargement Rapide', 'Réactif', 'Look Professionnel'],
    features_ar: ['تصميم حديث', 'تحميل سريع', 'متجاوب', 'مظهر احترافي'],
    features_de: ['Modernes Design', 'Schnelles Laden', 'Responsiv', 'Professioneller Look'],
    price_range_dzd: '200,000 - 1,000,000 DZD',
    price_range_eur: '1,000 - 5,000 €',
    price_range_usd: '$1,000 - $5,000',
    is_featured: true,
    display_order: 2,
  },
  {
    slug: 'ai-data',
    icon: 'Brain',
    title_en: 'AI & Data, made practical',
    title_fr: 'IA & Données, rendues pratiques',
    title_ar: 'الذكاء الاصطناعي والبيانات بشكل عملي',
    title_de: 'KI & Daten, praktisch gemacht',
    description_en: 'We help you use AI and data to automate tasks, understand your customers, and make better decisions.',
    description_fr: 'Nous vous aidons à utiliser l\'IA et les données pour automatiser les tâches, comprendre vos clients et prendre de meilleures décisions.',
    description_ar: 'نساعدك على استخدام الذكاء الاصطناعي والبيانات لأتمتة المهام وفهم عملائك واتخاذ قرارات أفضل.',
    description_de: 'Wir helfen Ihnen, KI und Daten zu nutzen, um Aufgaben zu automatisieren, Ihre Kunden zu verstehen und bessere Entscheidungen zu treffen.',
    features_en: ['Task Automation', 'Customer Insights', 'Data Analysis', 'Better Decisions'],
    features_fr: ['Automatisation des Tâches', 'Insights Clients', 'Analyse de Données', 'Meilleures Décisions'],
    features_ar: ['أتمتة المهام', 'رؤى العملاء', 'تحليل البيانات', 'قرارات أفضل'],
    features_de: ['Aufgabenautomatisierung', 'Kundeneinblicke', 'Datenanalyse', 'Bessere Entscheidungen'],
    price_range_dzd: '300,000 - 1,500,000 DZD',
    price_range_eur: '1,500 - 7,500 €',
    price_range_usd: '$1,500 - $7,500',
    is_featured: true,
    display_order: 3,
  },
  {
    slug: 'branding',
    icon: 'Sparkles',
    title_en: 'Branding & Identity',
    title_fr: 'Branding & Identité',
    title_ar: 'العلامة التجارية والهوية',
    title_de: 'Branding & Identität',
    description_en: 'Complete brand identity including logo, colors, and brand guidelines',
    description_fr: 'Identité de marque complète incluant logo, couleurs et directives de marque',
    description_ar: 'هوية علامة تجارية كاملة تشمل الشعار والألوان وإرشادات العلامة التجارية',
    description_de: 'Vollständige Markenidentität einschließlich Logo, Farben und Markenrichtlinien',
    features_en: ['Logo Design', 'Brand Guidelines', 'Business Cards', 'Marketing Materials'],
    features_fr: ['Design de Logo', 'Directives de Marque', 'Cartes de Visite', 'Matériel Marketing'],
    features_ar: ['تصميم الشعار', 'إرشادات العلامة التجارية', 'بطاقات العمل', 'مواد تسويقية'],
    features_de: ['Logo-Design', 'Markenrichtlinien', 'Visitenkarten', 'Marketingmaterialien'],
    price_range_dzd: '100,000 - 400,000 DZD',
    price_range_eur: '500 - 2,000 €',
    price_range_usd: '$500 - $2,000',
    is_featured: false,
    display_order: 4,
  },
  {
    slug: 'digital-marketing',
    icon: 'TrendingUp',
    title_en: 'Digital Marketing',
    title_fr: 'Marketing Digital',
    title_ar: 'التسويق الرقمي',
    title_de: 'Digitales Marketing',
    description_en: 'Grow your business with strategic digital marketing campaigns',
    description_fr: 'Développez votre entreprise avec des campagnes de marketing digital stratégiques',
    description_ar: 'نمّ عملك من خلال حملات تسويق رقمي استراتيجية',
    description_de: 'Wachsen Sie Ihr Unternehmen mit strategischen digitalen Marketingkampagnen',
    features_en: ['SEO & SEM', 'Social Media', 'Content Marketing', 'Analytics'],
    features_fr: ['SEO & SEM', 'Réseaux Sociaux', 'Marketing de Contenu', 'Analytiques'],
    features_ar: ['تحسين محركات البحث', 'وسائل التواصل الاجتماعي', 'تسويق المحتوى', 'التحليلات'],
    features_de: ['SEO & SEM', 'Social Media', 'Content-Marketing', 'Analytics'],
    price_range_dzd: '50,000 - 300,000 DZD/month',
    price_range_eur: '250 - 1,500 €/month',
    price_range_usd: '$250 - $1,500/month',
    is_featured: false,
    display_order: 5,
  },
  {
    slug: 'consulting',
    icon: 'Lightbulb',
    title_en: 'IT Consulting',
    title_fr: 'Conseil IT',
    title_ar: 'الاستشارات التقنية',
    title_de: 'IT-Beratung',
    description_en: 'Expert guidance for your digital transformation journey',
    description_fr: 'Conseils d\'experts pour votre parcours de transformation digitale',
    description_ar: 'إرشادات خبراء لرحلة التحول الرقمي الخاصة بك',
    description_de: 'Expertenberatung für Ihre digitale Transformation',
    features_en: ['Technology Strategy', 'Digital Transformation', 'Project Management', 'Team Training'],
    features_fr: ['Stratégie Technologique', 'Transformation Digitale', 'Gestion de Projet', 'Formation d\'Équipe'],
    features_ar: ['استراتيجية التكنولوجيا', 'التحول الرقمي', 'إدارة المشاريع', 'تدريب الفريق'],
    features_de: ['Technologiestrategie', 'Digitale Transformation', 'Projektmanagement', 'Teamtraining'],
    price_range_dzd: '100,000 - 500,000 DZD',
    price_range_eur: '500 - 2,500 €',
    price_range_usd: '$500 - $2,500',
    is_featured: false,
    display_order: 6,
  },
];

export const defaultFAQs: Omit<FAQ, 'id' | 'created_at' | 'updated_at'>[] = [
  {
    question_en: 'How long does it take to complete a project?',
    question_fr: 'Combien de temps faut-il pour terminer un projet ?',
    question_ar: 'كم من الوقت يستغرق إكمال المشروع؟',
    question_de: 'Wie lange dauert es, ein Projekt abzuschließen?',
    answer_en: 'Project timelines vary based on complexity. A typical website takes 4-8 weeks, while mobile apps can take 8-16 weeks. We provide detailed timelines during the consultation phase.',
    answer_fr: 'Les délais de projet varient selon la complexité. Un site web typique prend 4-8 semaines, tandis que les applications mobiles peuvent prendre 8-16 semaines. Nous fournissons des délais détaillés lors de la phase de consultation.',
    answer_ar: 'تختلف الجداول الزمنية للمشروع بناءً على التعقيد. يستغرق الموقع النموذجي من 4-8 أسابيع، بينما يمكن أن تستغرق تطبيقات الجوال من 8-16 أسبوعًا. نقدم جداول زمنية مفصلة أثناء مرحلة الاستشارة.',
    answer_de: 'Die Projektdauer variiert je nach Komplexität. Eine typische Website dauert 4-8 Wochen, während mobile Apps 8-16 Wochen in Anspruch nehmen können. Wir stellen detaillierte Zeitpläne während der Beratungsphase bereit.',
    category: 'general',
    display_order: 1,
  },
  {
    question_en: 'What is your pricing structure?',
    question_fr: 'Quelle est votre structure de prix ?',
    question_ar: 'ما هو هيكل التسعير الخاص بكم؟',
    question_de: 'Wie ist Ihre Preisstruktur?',
    answer_en: 'We offer flexible pricing based on project scope and requirements. We support multiple currencies (DZD, EUR, USD) and provide detailed quotes after understanding your needs. Contact us for a free consultation.',
    answer_fr: 'Nous offrons des prix flexibles basés sur la portée et les exigences du projet. Nous supportons plusieurs devises (DZD, EUR, USD) et fournissons des devis détaillés après avoir compris vos besoins. Contactez-nous pour une consultation gratuite.',
    answer_ar: 'نقدم أسعارًا مرنة بناءً على نطاق المشروع ومتطلباته. ندعم عملات متعددة (DZD، EUR، USD) ونقدم عروض أسعار مفصلة بعد فهم احتياجاتك. اتصل بنا للحصول على استشارة مجانية.',
    answer_de: 'Wir bieten flexible Preise basierend auf Projektumfang und Anforderungen. Wir unterstützen mehrere Währungen (DZD, EUR, USD) und stellen detaillierte Angebote bereit, nachdem wir Ihre Bedürfnisse verstanden haben. Kontaktieren Sie uns für eine kostenlose Beratung.',
    category: 'pricing',
    display_order: 2,
  },
  {
    question_en: 'Do you provide ongoing support and maintenance?',
    question_fr: 'Fournissez-vous un support et une maintenance continus ?',
    question_ar: 'هل تقدمون الدعم والصيانة المستمرة؟',
    question_de: 'Bieten Sie fortlaufenden Support und Wartung an?',
    answer_en: 'Yes! We offer comprehensive maintenance packages including security updates, performance monitoring, bug fixes, and feature enhancements. Support plans can be customized to your needs.',
    answer_fr: 'Oui ! Nous offrons des forfaits de maintenance complets incluant les mises à jour de sécurité, la surveillance des performances, les corrections de bugs et les améliorations de fonctionnalités. Les plans de support peuvent être personnalisés selon vos besoins.',
    answer_ar: 'نعم! نقدم حزم صيانة شاملة تشمل تحديثات الأمان ومراقبة الأداء وإصلاح الأخطاء وتحسينات الميزات. يمكن تخصيص خطط الدعم وفقًا لاحتياجاتك.',
    answer_de: 'Ja! Wir bieten umfassende Wartungspakete einschließlich Sicherheitsupdates, Leistungsüberwachung, Fehlerbehebungen und Feature-Verbesserungen. Support-Pläne können an Ihre Bedürfnisse angepasst werden.',
    category: 'support',
    display_order: 3,
  },
  {
    question_en: 'What technologies do you use?',
    question_fr: 'Quelles technologies utilisez-vous ?',
    question_ar: 'ما هي التقنيات التي تستخدمونها؟',
    question_de: 'Welche Technologien nutzen Sie?',
    answer_en: 'We work with modern, industry-standard technologies including React, Next.js, Node.js, Firebase, and more. We choose the best tech stack for each project based on your specific requirements.',
    answer_fr: 'Nous travaillons avec des technologies modernes et standard de l\'industrie incluant React, Next.js, Node.js, Firebase, et plus encore. Nous choisissons la meilleure pile technologique pour chaque projet en fonction de vos besoins spécifiques.',
    answer_ar: 'نعمل بتقنيات حديثة ومعتمدة في الصناعة بما في ذلك React وNext.js وNode.js وFirebase والمزيد. نختار أفضل مجموعة تقنية لكل مشروع بناءً على متطلباتك المحددة.',
    answer_de: 'Wir arbeiten mit modernen Industriestandard-Technologien wie React, Next.js, Node.js, Firebase und mehr. Wir wählen den besten Tech-Stack für jedes Projekt basierend auf Ihren spezifischen Anforderungen.',
    category: 'technical',
    display_order: 4,
  },
  {
    question_en: 'Can you work with clients internationally?',
    question_fr: 'Pouvez-vous travailler avec des clients internationaux ?',
    question_ar: 'هل يمكنكم العمل مع عملاء دوليين؟',
    question_de: 'Können Sie mit internationalen Kunden arbeiten?',
    answer_en: 'Absolutely! We work with clients worldwide. We support multiple currencies and languages, and use modern collaboration tools to ensure seamless communication regardless of location.',
    answer_fr: 'Absolument ! Nous travaillons avec des clients du monde entier. Nous supportons plusieurs devises et langues, et utilisons des outils de collaboration modernes pour assurer une communication fluide quelle que soit votre localisation.',
    answer_ar: 'بالتأكيد! نعمل مع عملاء من جميع أنحاء العالم. ندعم عملات ولغات متعددة، ونستخدم أدوات تعاون حديثة لضمان التواصل السلس بغض النظر عن الموقع.',
    answer_de: 'Absolut! Wir arbeiten mit Kunden weltweit. Wir unterstützen mehrere Währungen und Sprachen und nutzen moderne Kollaborationstools, um eine nahtlose Kommunikation unabhängig vom Standort zu gewährleisten.',
    category: 'general',
    display_order: 5,
  },
  {
    question_en: 'Do you offer custom solutions or just templates?',
    question_fr: 'Proposez-vous des solutions personnalisées ou seulement des modèles ?',
    question_ar: 'هل تقدمون حلولاً مخصصة أم قوالب فقط؟',
    question_de: 'Bieten Sie maßgeschneiderte Lösungen oder nur Vorlagen?',
    answer_en: 'We specialize in custom solutions tailored to your unique business needs. While we use proven frameworks and best practices, every project is built specifically for you, not from generic templates.',
    answer_fr: 'Nous nous spécialisons dans les solutions personnalisées adaptées à vos besoins commerciaux uniques. Bien que nous utilisions des frameworks éprouvés et des meilleures pratiques, chaque projet est construit spécifiquement pour vous, pas à partir de modèles génériques.',
    answer_ar: 'نتخصص في الحلول المخصصة المصممة خصيصًا لاحتياجات عملك الفريدة. بينما نستخدم أطر عمل مثبتة وأفضل الممارسات، يتم بناء كل مشروع خصيصًا لك، وليس من قوالب عامة.',
    answer_de: 'Wir sind spezialisiert auf maßgeschneiderte Lösungen, die auf Ihre einzigartigen Geschäftsbedürfnisse zugeschnitten sind. Obwohl wir bewährte Frameworks und Best Practices verwenden, wird jedes Projekt speziell für Sie erstellt, nicht aus generischen Vorlagen.',
    category: 'services',
    display_order: 6,
  },
];

export const defaultSiteSettings: Omit<SiteSettings, 'id' | 'updated_at'> = {
  site_name: 'DZenix',
  tagline_en: 'Transform Your Digital Vision',
  tagline_fr: 'Transformez Votre Vision Digitale',
  tagline_ar: 'حوّل رؤيتك الرقمية',
  tagline_de: 'Verwandeln Sie Ihre digitale Vision',
  description_en: 'Professional digital agency specializing in web development, mobile apps, and digital solutions',
  description_fr: 'Agence digitale professionnelle spécialisée dans le développement web, les applications mobiles et les solutions digitales',
  description_ar: 'وكالة رقمية محترفة متخصصة في تطوير الويب وتطبيقات الجوال والحلول الرقمية',
  description_de: 'Professionelle Digitalagentur spezialisiert auf Webentwicklung, mobile Apps und digitale Lösungen',
  contact_email: 'contact@dzenix.com',
  contact_phone: '+213 XXX XX XX XX',
  address_en: 'Algiers, Algeria',
  address_fr: 'Alger, Algérie',
  address_ar: 'الجزائر، الجزائر',
  address_de: 'Algier, Algerien',
  whatsapp_number_1: '+43 660 8439375',
  whatsapp_number_2: '+43 660 2313221',
  whatsapp_message_en: 'Hello! I would like to inquire about your services.',
  whatsapp_message_fr: 'Bonjour! Je voudrais me renseigner sur vos services.',
  whatsapp_message_ar: 'مرحباً! أود الاستفسار عن خدماتكم.',
  whatsapp_message_de: 'Hallo! Ich würde gerne mehr über Ihre Dienstleistungen erfahren.',
  social_facebook: 'https://facebook.com/dzenix',
  social_twitter: 'https://twitter.com/dzenix',
  social_linkedin: 'https://linkedin.com/company/dzenix',
  social_instagram: 'https://instagram.com/dzenix',
  primary_color: '#2563eb',
  secondary_color: '#ffffff',
  logo_url: '/dzenix.png',
  logo_width: 40,
  logo_height: 40,
  logo_alt_en: 'DZenix Logo',
  logo_alt_fr: 'Logo DZenix',
  logo_alt_ar: 'شعار DZenix',
  logo_alt_de: 'DZenix Logo',
  pattern_enabled: true,
  pattern_opacity_light: 8,
  pattern_opacity_dark: 12,
  pattern_scale: 370,
  pattern_stroke_width: 1,
  pattern_color_light: '#2563eb',
  pattern_color_dark: '#ffffff',
  pattern_enabled_sections: ['hero', 'services', 'why-choose', 'process', 'who-we-work-with', 'cta', 'footer', 'contact'],
  default_meta_title: 'DZenix - Transform Your Digital Vision',
  default_meta_description: 'Professional digital agency in Algeria specializing in web development, mobile apps, UI/UX design, and digital solutions',
  default_meta_keywords: 'web development, mobile apps, digital agency, Algeria, UI/UX design, software development',
  default_og_image: '/dzenix.png',
  site_base_url: 'https://dzenix.com',
};

export const defaultPages: Omit<Page, 'id' | 'created_at' | 'updated_at'>[] = [
  {
    slug: 'home',
    title_en: 'Home',
    title_fr: 'Accueil',
    title_ar: 'الرئيسية',
    title_de: 'Startseite',
    meta_title_en: 'DZenix - Transform Your Digital Vision',
    meta_title_fr: 'DZenix - Transformez Votre Vision Digitale',
    meta_title_ar: 'DZenix - حوّل رؤيتك الرقمية',
    meta_title_de: 'DZenix - Verwandeln Sie Ihre digitale Vision',
    meta_description_en: 'Professional digital agency in Algeria specializing in web development, mobile apps, UI/UX design, and digital solutions',
    meta_description_fr: 'Agence digitale professionnelle en Algérie spécialisée dans le développement web, les applications mobiles, le design UI/UX et les solutions digitales',
    meta_description_ar: 'وكالة رقمية محترفة في الجزائر متخصصة في تطوير الويب وتطبيقات الجوال وتصميم واجهة المستخدم والحلول الرقمية',
    meta_description_de: 'Professionelle Digitalagentur in Algerien spezialisiert auf Webentwicklung, mobile Apps, UI/UX-Design und digitale Lösungen',
    meta_keywords_en: 'web development, mobile apps, digital agency, Algeria, UI/UX design',
    meta_keywords_fr: 'développement web, applications mobiles, agence digitale, Algérie, design UI/UX',
    meta_keywords_ar: 'تطوير الويب، تطبيقات الجوال، وكالة رقمية، الجزائر، تصميم واجهة المستخدم',
    meta_keywords_de: 'Webentwicklung, mobile Apps, Digitalagentur, Algerien, UI/UX-Design',
    robots_index: true,
    is_published: true,
  },
  {
    slug: 'services',
    title_en: 'Services',
    title_fr: 'Services',
    title_ar: 'الخدمات',
    title_de: 'Dienstleistungen',
    meta_title_en: 'Our Services - DZenix',
    meta_title_fr: 'Nos Services - DZenix',
    meta_title_ar: 'خدماتنا - DZenix',
    meta_title_de: 'Unsere Dienstleistungen - DZenix',
    meta_description_en: 'Explore our comprehensive digital services: web development, mobile apps, UI/UX design, branding, and more',
    meta_description_fr: 'Découvrez nos services digitaux complets : développement web, applications mobiles, design UI/UX, branding, et plus',
    meta_description_ar: 'استكشف خدماتنا الرقمية الشاملة: تطوير الويب وتطبيقات الجوال وتصميم واجهة المستخدم والعلامة التجارية والمزيد',
    meta_description_de: 'Entdecken Sie unsere umfassenden digitalen Dienstleistungen: Webentwicklung, mobile Apps, UI/UX-Design, Branding und mehr',
    meta_keywords_en: 'web services, app development services, UI/UX design services, digital solutions',
    meta_keywords_fr: 'services web, services de développement d\'applications, services de design UI/UX, solutions digitales',
    meta_keywords_ar: 'خدمات الويب، خدمات تطوير التطبيقات، خدمات تصميم واجهة المستخدم، الحلول الرقمية',
    meta_keywords_de: 'Webdienste, App-Entwicklungsdienste, UI/UX-Designdienste, digitale Lösungen',
    robots_index: true,
    is_published: true,
  },
  {
    slug: 'contact',
    title_en: 'Contact',
    title_fr: 'Contact',
    title_ar: 'اتصل بنا',
    title_de: 'Kontakt',
    meta_title_en: 'Contact Us - DZenix',
    meta_title_fr: 'Contactez-Nous - DZenix',
    meta_title_ar: 'اتصل بنا - DZenix',
    meta_title_de: 'Kontaktieren Sie uns - DZenix',
    meta_description_en: 'Get in touch with DZenix for your digital project. We support multiple currencies and work with clients worldwide',
    meta_description_fr: 'Contactez DZenix pour votre projet digital. Nous supportons plusieurs devises et travaillons avec des clients du monde entier',
    meta_description_ar: 'تواصل مع DZenix لمشروعك الرقمي. ندعم عملات متعددة ونعمل مع عملاء من جميع أنحاء العالم',
    meta_description_de: 'Kontaktieren Sie DZenix für Ihr digitales Projekt. Wir unterstützen mehrere Währungen und arbeiten mit Kunden weltweit',
    meta_keywords_en: 'contact DZenix, digital agency contact, web development quote, app development inquiry',
    meta_keywords_fr: 'contact DZenix, contact agence digitale, devis développement web, demande développement d\'applications',
    meta_keywords_ar: 'اتصل بـ DZenix، اتصال وكالة رقمية، عرض أسعار تطوير الويب، استفسار تطوير التطبيقات',
    meta_keywords_de: 'DZenix kontaktieren, Digitalagentur Kontakt, Webentwicklungsangebot, App-Entwicklungsanfrage',
    robots_index: true,
    is_published: true,
  },
];

export const defaultSections: Omit<Section, 'id' | 'created_at' | 'updated_at'>[] = [
  {
    page_slug: 'home',
    section_type: 'hero',
    title_en: 'We build the digital products you imagine.',
    title_fr: 'Nous construisons les produits numériques que vous imaginez.',
    title_ar: 'نبني المنتجات الرقمية التي تتخيلها.',
    title_de: 'Wir bauen die digitalen Produkte, die Sie sich vorstellen.',
    subtitle_en: 'Your idea, we build it.',
    subtitle_fr: 'Votre idée, nous la construisons.',
    subtitle_ar: 'فكرتك، نحن نبنيها.',
    subtitle_de: 'Ihre Idee, wir setzen sie um.',
    content_en: 'DZenix SARL is a tech studio based in Algeria, specialized in custom app development, website creation, and AI/data services. We partner with startups, brands, and companies to turn ideas into real digital products — from the first prototype to scalable platforms. With a mix of UX design, solid engineering, and smart automation, DZenix helps clients launch faster, work smarter, and offer better experiences to their users.',
    content_fr: 'DZenix SARL est un studio technologique basé en Algérie, spécialisé dans le développement d\'applications personnalisées, la création de sites web et les services IA/données. Nous nous associons avec des startups, des marques et des entreprises pour transformer les idées en produits numériques réels — du premier prototype aux plateformes évolutives. Avec un mélange de design UX, d\'ingénierie solide et d\'automatisation intelligente, DZenix aide les clients à lancer plus rapidement, à travailler plus intelligemment et à offrir de meilleures expériences à leurs utilisateurs.',
    content_ar: 'DZenix SARL هو استوديو تقني مقره الجزائر، متخصص في تطوير التطبيقات المخصصة وإنشاء المواقع الإلكترونية وخدمات الذكاء الاصطناعي والبيانات. نتعاون مع الشركات الناشئة والعلامات التجارية والشركات لتحويل الأفكار إلى منتجات رقمية حقيقية - من النموذج الأولي الأول إلى المنصات القابلة للتطوير. من خلال مزيج من تصميم تجربة المستخدم والهندسة القوية والأتمتة الذكية، تساعد DZenix العملاء على الإطلاق بشكل أسرع والعمل بذكاء أكبر وتقديم تجارب أفضل لمستخدميهم.',
    content_de: 'DZenix SARL ist ein Techstudio mit Sitz in Algerien, spezialisiert auf individuelle App-Entwicklung, Website-Erstellung und KI/Daten-Services. Wir arbeiten mit Startups, Marken und Unternehmen zusammen, um Ideen in echte digitale Produkte zu verwandeln - vom ersten Prototyp bis zu skalierbaren Plattformen. Mit einer Mischung aus UX-Design, solider Technik und intelligenter Automatisierung hilft DZenix Kunden, schneller zu starten, smarter zu arbeiten und bessere Erfahrungen für ihre Nutzer zu bieten.',
    cta_text_en: 'Start Your Project',
    cta_text_fr: 'Démarrez Votre Projet',
    cta_text_ar: 'ابدأ مشروعك',
    cta_text_de: 'Starten Sie Ihr Projekt',
    cta_link: '/contact',
    display_order: 1,
  },
  {
    page_slug: 'home',
    section_type: 'services_overview',
    title_en: 'What we can build for you :',
    title_fr: 'Ce que nous pouvons construire pour vous :',
    title_ar: 'ما يمكننا بناؤه لك :',
    title_de: 'Was wir für Sie entwickeln können:',
    subtitle_en: '',
    subtitle_fr: '',
    subtitle_ar: '',
    subtitle_de: '',
    content_en: '',
    content_fr: '',
    content_ar: '',
    content_de: '',
    display_order: 2,
  },
  {
    page_slug: 'home',
    section_type: 'why_choose',
    title_en: 'Why teams choose DZenix as their tech partner',
    title_fr: 'Pourquoi les équipes choisissent DZenix comme partenaire technologique',
    title_ar: 'لماذا تختار الفرق DZenix كشريك تقني',
    title_de: 'Warum Teams DZenix als ihren Tech-Partner wählen',
    subtitle_en: '',
    subtitle_fr: '',
    subtitle_ar: '',
    subtitle_de: '',
    content_en: 'From idea to launch – Come with a raw idea; leave with a working product. We cover design, development, and support.\n\nClear communication – No technical jargon, just simple explanations, regular updates, and honest timelines.\n\nModern, scalable tech – We build with technologies that can grow with your business, not limit it.\n\nLocal insight, global quality – We understand the Algerian & MENA context while following international standards.',
    content_fr: 'De l\'idée au lancement – Venez avec une idée brute ; repartez avec un produit fonctionnel. Nous couvrons le design, le développement et le support.\n\nCommunication claire – Pas de jargon technique, juste des explications simples, des mises à jour régulières et des délais honnêtes.\n\nTechnologie moderne et évolutive – Nous construisons avec des technologies qui peuvent grandir avec votre entreprise, pas la limiter.\n\nPerspective locale, qualité mondiale – Nous comprenons le contexte algérien et MENA tout en suivant les normes internationales.',
    content_ar: 'من الفكرة إلى الإطلاق - تعال بفكرة خام؛ غادر بمنتج عامل. نغطي التصميم والتطوير والدعم.\n\nتواصل واضح - لا مصطلحات تقنية، فقط شروحات بسيطة وتحديثات منتظمة وجداول زمنية صادقة.\n\nتقنية حديثة وقابلة للتطوير - نبني بتقنيات يمكن أن تنمو مع عملك، وليس تحديده.\n\nرؤية محلية، جودة عالمية - نفهم السياق الجزائري والشرق أوسطي مع اتباع المعايير الدولية.',
    content_de: 'Von der Idee zum Launch – Kommen Sie mit einer rohen Idee; gehen Sie mit einem funktionierenden Produkt. Wir decken Design, Entwicklung und Support ab.\n\nKlare Kommunikation – Kein technischer Jargon, nur einfache Erklärungen, regelmäßige Updates und ehrliche Zeitpläne.\n\nModerne, skalierbare Technologie – Wir bauen mit Technologien, die mit Ihrem Unternehmen wachsen können, nicht es einschränken.\n\nLokale Einblicke, globale Qualität – Wir verstehen den algerischen & MENA-Kontext und folgen gleichzeitig internationalen Standards.',
    display_order: 3,
  },
  {
    page_slug: 'home',
    section_type: 'process',
    title_en: 'Our process: simple and transparent',
    title_fr: 'Notre processus : simple et transparent',
    title_ar: 'عمليتنا: بسيطة وشفافة',
    title_de: 'Unser Prozess: einfach und transparent',
    subtitle_en: '',
    subtitle_fr: '',
    subtitle_ar: '',
    subtitle_de: '',
    content_en: '1. Discover\nWe listen to your idea, goals, and constraints (budget, deadline, market) and advise you on the best approach.\n\n2. Design & Plan\nWe define the features, create basic UX flows or mockups, and give you a clear quote and timeline.\n\n3. Build\nOur team develops your app, website, or AI solution with regular demos so you see progress.\n\n4. Launch & Grow\nWe deploy, monitor, fix issues, and help you improve based on real user feedback.',
    content_fr: '1. Découvrir\nNous écoutons votre idée, vos objectifs et vos contraintes (budget, délai, marché) et vous conseillons sur la meilleure approche.\n\n2. Concevoir & Planifier\nNous définissons les fonctionnalités, créons des flux UX de base ou des maquettes, et vous donnons un devis clair et un calendrier.\n\n3. Construire\nNotre équipe développe votre application, site web ou solution IA avec des démos régulières pour que vous puissiez voir les progrès.\n\n4. Lancer & Grandir\nNous déployons, surveillons, corrigeons les problèmes et vous aidons à améliorer en fonction des retours réels des utilisateurs.',
    content_ar: '1. اكتشف\nنستمع إلى فكرتك وأهدافك وقيودك (الميزانية والموعد النهائي والسوق) وننصحك بأفضل نهج.\n\n2. التصميم والتخطيط\nنحدد الميزات ونخلق تدفقات تجربة المستخدم الأساسية أو النماذج ونعطيك عرض أسعار واضح وجدول زمني.\n\n3. البناء\nيطور فريقنا تطبيقك أو موقعك الإلكتروني أو حل الذكاء الاصطناعي مع عروض توضيحية منتظمة حتى ترى التقدم.\n\n4. الإطلاق والنمو\nنقوم بالنشر والمراقبة وإصلاح المشكلات ومساعدتك على التحسين بناءً على ملاحظات المستخدمين الحقيقية.',
    content_de: '1. Entdecken\nWir hören uns Ihre Idee, Ziele und Einschränkungen (Budget, Deadline, Markt) an und beraten Sie über den besten Ansatz.\n\n2. Design & Planung\nWir definieren die Features, erstellen grundlegende UX-Flows oder Mockups und geben Ihnen ein klares Angebot und einen Zeitplan.\n\n3. Entwickeln\nUnser Team entwickelt Ihre App, Website oder KI-Lösung mit regelmäßigen Demos, damit Sie den Fortschritt sehen.\n\n4. Launch & Wachstum\nWir deployen, überwachen, beheben Probleme und helfen Ihnen basierend auf echtem Nutzer-Feedback zu verbessern.',
    display_order: 4,
  },
  {
    page_slug: 'home',
    section_type: 'who_we_work_with',
    title_en: 'Made for startups, SMEs, and ambitious teams',
    title_fr: 'Conçu pour les startups, les PME et les équipes ambitieuses',
    title_ar: 'مصمم للشركات الناشئة والشركات الصغيرة والمتوسطة والفرق الطموحة',
    title_de: 'Gemacht für Startups, KMUs und ambitionierte Teams',
    subtitle_en: '',
    subtitle_fr: '',
    subtitle_ar: '',
    subtitle_de: '',
    content_en: 'Whether you\'re launching a new startup, digitalizing your company, or upgrading an old system, DZenix helps you move from idea to working solution quickly and safely.',
    content_fr: 'Que vous lanciez une nouvelle startup, digitalisiez votre entreprise ou mettiez à niveau un ancien système, DZenix vous aide à passer de l\'idée à la solution fonctionnelle rapidement et en toute sécurité.',
    content_ar: 'سواء كنت تطلق شركة ناشئة جديدة أو ترقمن شركتك أو تقوم بترقية نظام قديم، تساعدك DZenix على الانتقال من الفكرة إلى الحل العملي بسرعة وأمان.',
    content_de: 'Ob Sie ein neues Startup starten, Ihr Unternehmen digitalisieren oder ein altes System aktualisieren – DZenix hilft Ihnen, schnell und sicher von der Idee zur funktionierenden Lösung zu gelangen.',
    display_order: 5,
  },
  {
    page_slug: 'home',
    section_type: 'final_cta',
    title_en: 'Ready to build your next project?',
    title_fr: 'Prêt à construire votre prochain projet ?',
    title_ar: 'هل أنت مستعد لبناء مشروعك التالي؟',
    title_de: 'Bereit, Ihr nächstes Projekt zu starten?',
    subtitle_en: '',
    subtitle_fr: '',
    subtitle_ar: '',
    subtitle_de: '',
    content_en: 'Tell us about your idea and we\'ll get back to you with a free estimate and a simple plan.',
    content_fr: 'Parlez-nous de votre idée et nous vous recontacterons avec une estimation gratuite et un plan simple.',
    content_ar: 'أخبرنا عن فكرتك وسنعود إليك بتقدير مجاني وخطة بسيطة.',
    content_de: 'Erzählen Sie uns von Ihrer Idee und wir melden uns mit einer kostenlosen Schätzung und einem einfachen Plan bei Ihnen zurück.',
    cta_text_en: 'Describe your project',
    cta_text_fr: 'Décrivez votre projet',
    cta_text_ar: 'صف مشروعك',
    cta_text_de: 'Beschreiben Sie Ihr Projekt',
    cta_link: '/contact',
    display_order: 6,
  },
  {
    page_slug: 'contact',
    section_type: 'contact_intro',
    title_en: 'Let\'s Build Something Great Together',
    title_fr: 'Construisons Quelque Chose de Grand Ensemble',
    title_ar: 'لنبني شيئًا رائعًا معًا',
    title_de: 'Lassen Sie uns gemeinsam etwas Großartiges aufbauen',
    subtitle_en: 'Get in Touch',
    subtitle_fr: 'Contactez-Nous',
    subtitle_ar: 'تواصل معنا',
    subtitle_de: 'Kontaktieren Sie uns',
    content_en: 'Ready to start your project? Fill out the form below and our team will get back to you within 24 hours. We support multiple currencies and work with clients worldwide.',
    content_fr: 'Prêt à démarrer votre projet ? Remplissez le formulaire ci-dessous et notre équipe vous répondra dans les 24 heures. Nous supportons plusieurs devises et travaillons avec des clients du monde entier.',
    content_ar: 'هل أنت مستعد لبدء مشروعك؟ املأ النموذج أدناه وسيعود فريقنا إليك في غضون 24 ساعة. ندعم عملات متعددة ونعمل مع عملاء من جميع أنحاء العالم.',
    content_de: 'Bereit, Ihr Projekt zu starten? Füllen Sie das untenstehende Formular aus und unser Team wird sich innerhalb von 24 Stunden bei Ihnen melden. Wir unterstützen mehrere Währungen und arbeiten mit Kunden weltweit.',
    display_order: 1,
  },
];
